# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3.2 1B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-3.2-1B-Instruct --output-dir /tmp/Llama-3.2-1B-Instruct --ignore-patterns "original/consolidated.00.pth"
#
# To launch on 4 devices, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 1B_full_single_device.yaml for those cases


# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  # path: /data/nvme3n1p1/adal_workspace/pseudo_train/KazLLM_Bee/tokenizers/llama3-1-tokenizer_kk_plus_26
  path: /data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/llama3_2_1b_Instruct
  max_seq_len: 8192

# Dataset
dataset:
  _component_: torchtune.datasets.instruct_dataset
  source: json
  split: train
  # data_files: /data/nvme7n1p1/critical_all/critical_instruct/*.json
  data_files: /data/nvme7n1p1/critical_all/critical_instruct/*.json
  template: torchtune.data.AlpacaInstructTemplate
  column_map:
    instruction: instruction
    input: input
    output: output
  max_seq_len: 8192
  packed: False
seed: null
shuffle: False
max_seq_len: 8192
# Model Arguments
model:
  _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/llama3_2_1b_Instruct
  checkpoint_files: [
    model.safetensors
  ]
  recipe_checkpoint: null
  output_dir: /data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/checkpoints/correct_mask_1b_sft
  model_type: LLAMA3_2
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 2
epochs: 3

optimizer:
  _component_: torch.optim.AdamW
  lr: 2e-5
  fused: True
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null
gradient_accumulation_steps: 4


# Training env
device: cuda

# Memory management
enable_activation_checkpointing: False
compile: False # set it to True for better memory and performance

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
output_dir: /data/nvme3n1p1/adal_workspace/new_era_of_3.2/torchtune/logs
log_every_n_steps: 1
log_peak_memory_stats: False

# metric_logger:
#   _component_: torchtune.training.metric_logging.WandBLogger
#   # the W&B project to log to
#   project: 1b_llama
#   name: 1B_base_8192_it_fixed_batch_size_maskv2
# output_dir: /data/nvme3n1p1/adal_workspace/db9_train/KazLLM_Bee/logs_inst
# log_every_n_steps: 1
# log_peak_memory_stats: False

sub_length: 10000
# train_type: instruct
train_type: instruct